kafka:
  eventDateStore: consumer.event-date-store
  retentionDays: 14
  deleteIntervalMinutes: 1440 # 1 day
  consumerName: consumer-dev1
  upsellHostAssignmentsTopic: host_assignments
  bootstrap-servers: "localhost:9092"

kinesis:
  recordMaxBufferedTime: 100
  maxConnections: 4
  requestTimeout: 6000
  region: us-east-1
  stream: stream-consumer-dev1

logging:
  config: classpath:logback-fluent-nonprod.xml
