tm:
  service:
    descriptor:
      name: stream-consumer
      description: stream consumer
      distroList: rp@gmail.com
      onCallGroup: NONE
      productCode: 2020
      serviceTier: IMPORTANT
      documentationLink: todo
      contractLink: todo
      runbookLink: todo
      slack: none
      tags:
        - upsell
        - service

#server:
#  port: 8080
#
#management:
#  security:
#    enabled: false
#  port: 8081
#  context-path: /manage
#
#endpoints:
#  enabled: true
